// Sprite order
#define BACKGROUND	 0
#define TITLE		 1
#define START		 2
#define CREDITS		 3
#define MISSILE		 0
#define HPBACKGROUND 1
#define HEALTH		 2
#define SCORE		 3
#define PAUSED		 0
#define BACK		 1
#define GAMEOVER     0
